-- Job menu
--openJobMenu = function()
--    if not wsb.hasGroup(Config.policeJobs) then return end
--    if not wsb.isOnDuty() then return end
--    local _job, grade = wsb.hasGroup(Config.policeJobs)
--    local jobLabel = Strings.police
--    local Options = {}
--    if Config.searchPlayers then
--        Options[#Options + 1] = {
--            title = Strings.search_player,
--            description = Strings.search_player_desc,
--            icon = 'magnifying-glass',
--            arrow = false,
--            event = 'wasabi_police:searchPlayer',
--        }
--    end
--    Options[#Options + 1] = {
--        title = Strings.check_id,
--        description = Strings.check_id_desc,
--        icon = 'id-card',
--        arrow = true,
--        event = 'wasabi_police:checkId',
--    }
--    if Config?.GrantWeaponLicenses?.enabled and tonumber(grade or 0) >= Config.GrantWeaponLicenses.minGrade then
--        Options[#Options + 1] = {
--            title = Strings.grant_license,
--            description = Strings.grant_license_desc,
--            icon = 'id-card',
--            arrow = true,
--            event = 'wasabi_police:grantLicense',
--        }
--    end
--    if Config.Jail.enabled then
--        Options[#Options + 1] = {
--            title = Strings.jail_player,
--            description = Strings.jail_player_desc,
--            icon = 'lock',
--            arrow = false,
--            event = 'wasabi_police:sendToJail',
--        }
--    end
--    Options[#Options + 1] = {
--        title = Strings.handcuff_soft_player,
--        description = Strings.handcuff_soft_player_desc,
--        icon = 'hands-bound',
--        arrow = false,
--        args = { type = 'soft' },
--        event = 'wasabi_police:handcuffPlayer',
--    }
--    Options[#Options + 1] = {
--        title = Strings.handcuff_hard_player,
--        description = Strings.handcuff_hard_player_desc,
--        icon = 'hands-bound',
--        arrow = false,
--        args = { type = 'hard' },
--        event = 'wasabi_police:handcuffPlayer',
--    }
--    Options[#Options + 1] = {
--        title = Strings.escort_player,
--        description = Strings.escort_player_desc,
--        icon = 'hand-holding-hand',
--        arrow = false,
--        event = 'wasabi_police:escortPlayer',
--    }
--    if Config.GSR.enabled then
--        Options[#Options + 1] = {
--            title = Strings.gsr_test,
--            description = Strings.gsr_test_desc,
--            icon = 'gun',
--            arrow = false,
--            event = 'wasabi_police:gsrTest',
--        }
--    end
--    Options[#Options + 1] = {
--        title = Strings.put_in_vehicle,
--        description = Strings.put_in_vehicle_desc,
--        icon = 'arrow-right-to-bracket',
--        arrow = false,
--        event = 'wasabi_police:inVehiclePlayer',
--    }
--    Options[#Options + 1] = {
--        title = Strings.take_out_vehicle,
--        description = Strings.take_out_vehicle_desc,
--        icon = 'arrow-right-from-bracket',
--        arrow = false,
--        event = 'wasabi_police:outVehiclePlayer',
--    }
--    Options[#Options + 1] = {
--        title = Strings.vehicle_interactions,
--        description = Strings.vehicle_interactions_desc,
--        icon = 'car',
--        arrow = true,
--        event = 'wasabi_police:vehicleInteractions',
--    }
--    Options[#Options + 1] = {
--        title = Strings.place_object,
--        description = Strings.place_object_desc,
--        icon = 'box',
--        arrow = true,
--        event = 'wasabi_police:placeObjects',
--    }
--    if Config.billingSystem then
--        Options[#Options + 1] = {
--            title = Strings.fines,
--            description = Strings.fines_desc,
--            icon = 'file-invoice',
--            arrow = false,
--            event = 'wasabi_police:finePlayer',
--        }
--    end
--    if Config.MobileMenu.enabled then
--		OpenMobileMenu('pd_job_menu', jobLabel, Options)
--	else
--        lib.registerContext({
--            id = 'pd_job_menu',
--            title = jobLabel,
--            options = Options
--        })
--        lib.showContext('pd_job_menu')
--    end
--end